[package]
name = "concurrent"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
atomic-wait = "1.1.0"
slab = "0.4.12"

[dev-dependencies]
criterion.workspace = true
trybuild.workspace = true
tokio = { version = "1", features = ["rt", "macros", "time"] }

[[bench]]
name = "backoff"
harness = false

[[bench]]
name = "parker"
harness = false

[[bench]]
name = "atomic_cell"
harness = false

[[bench]]
name = "false_sharing"
harness = false

[[bench]]
name = "semaphore"
harness = false

[[bench]]
name = "seq_lock"
harness = false

[lints]
workspace = true

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"
