import puppeteer from 'puppeteer';
const [,, htmlPath, outPath] = process.argv;
const b = await puppeteer.launch({ args: ['--no-sandbox'] });
const p = await b.newPage();
await p.setViewport({ width: 960, height: 1200, deviceScaleFactor: 2 });
await p.goto('file://' + htmlPath, { waitUntil: 'networkidle0' });
await p.evaluateHandle('document.fonts.ready');
await p.screenshot({ path: outPath, clip: { x: 0, y: 0, width: 960, height: 1200 } });
await b.close();
console.log('wrote', outPath);
