[package]
name = "eth-chain-state"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
eth-primitives.workspace = true
concurrent.workspace = true

[lints]
workspace = true

[target.'cfg(loom)'.dev-dependencies]
loom = "0.7.2"